FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build
WORKDIR /myapp

# copy csproj and restore as distinct layers
COPY *.sln .
COPY sampleproj/*.csproj ./sampleproj/
RUN dotnet restore

# copy everything else and build app
COPY sampleproj/. ./sampleproj/
WORKDIR /myapp/sampleproj
RUN dotnet publish -c Release -o out


FROM mcr.microsoft.com/dotnet/core/aspnet:2.2 AS runtime
WORKDIR /app
COPY --from=build /myapp/sampleproj/out ./
ENTRYPOINT ["dotnet", "aspnetapp.dll"]
